### ISSUE TITLE
Melee combat AC bonus & student skills

### ISSUE THREAD

**Issue by IYOV-git** [chrisesharp/foundryvtt-helveczia#13]
Hi,

first of all, thank you for your excellent work!

But I seem to have noticed a bug (or I'm missing something): polish & hungarian people get a +2 attack and AC bonus in melee combat. But it seems to me that the AC bonus is not taken into account when a polish/hungarian character is the target of a melee attack.

I also found it a bit confusing that "Spells" and "Doctorate" are listed as skills and that they count against the skill point maximum. Even though students get extra skill points to compensate for this, it seems easier to me to list them in the tab for the student class than to treat them as skills.

Best regards

**Comment by chrisesharp** [comment]
Hi @IYOV-git  - thank you :-) 

So, after a little investigation, I found that although Hungarians do get +2 to AC and melee, the Polish only get it to their melee....I need to fix this bug.

However, checking them as being the target of an attack, the Hungarian's AC bonus is being taken into account. Could you maybe take some screen shots to indicate where a Hungarian character's AC is not being used for the target number?

Regarding the confusing aspect of Spells and Doctorate listed as skills - they don't count against the skills really because the class adjusts the skill limit to take them into account. They appear as skills because they are implemented as skills in the system, and it's helpful for new players to realise their class abilities carry special skills as well (this is more obvious with the vagabond and fighter classes). I agree it would be nice to have them appear under the Student or Cleric tabs as appropriate...I'll look at that when I fix the Polish effects.

**Comment by IYOV-git** [comment]
You're absolutely right, the AC bug only affect the Polish. And I agree with you that it makes sense to list the class abilities somewhere, it might also be useful to include the abilities from your origin/people if they can't be covered by the system.

However, I noticed a few other small points during testing today:

NPCs:
- Determining the HP randomly via the sheet doesn't seem to include the level bonus (e.g. lvl 6+2 -> 5d8+8+0+0*5)
- Is there a way to determine two favoured saves (e.g. Devil, Mephisto +7/+5/+7)?
- If I use the import function, the saves are not transferred correctly (e.g. +7/+5/+7 -> +7/+5/+5).

Fighters:
- Removing specialisms also removes the fighter tab. (if you drag a specialism back onto the sheet, the tab is visible again)

Students:
- a button to randomise Sciences would be great (like "Roll for Random Craft" for Germans)

Main-gauche:
- an entry under armour like the Parrying Dagger would also be great (I know it's easy to create yourself, but I was a bit stumped at first when I tried to add the AC bonus for the weapon until I realised that I just had to create it as an armour item)

Swedes:
- no description
- also, sometimes the font changes at the end of the description (e.g. jewish, hungarian, czech, cossacks)

Of course, none of these are serious problems. Again, thank you!

**Comment by chrisesharp** [comment]
Great feedback, thank you! I've added a fix for the Polish AC...I'll address your other points below:

**NPCs:**
- [x] `Determining the HP randomly via the sheet doesn't seem to include the level bonus (e.g. lvl 6+2 -> 5d8+8+0+0*5)`
- [ ] `Is there a way to determine two favoured saves (e.g. Devil, Mephisto +7/+5/+7)?` 
I don't understand what you mean..can you elaborate?
- [ ] `If I use the import function, the saves are not transferred correctly (e.g. +7/+5/+7 -> +7/+5/+5).` 
The import code is a best attempt at interpreting the short version expressions the rule cites...like this
```
Krampus: LVL 3+2*; AC 15; Atk +5 fire poker
1d6+2 or +5 bundle of sticks 1d6+2 knockout or +5
chains; Spec immune to fire, chains, Climb +5;
+5/+3/+3; V 1d3.
Chains: can entangle with CC, Escape Artist frees.
Hp 18
```
It doesn't parse the full entries.

I have actually created ALL the content from the rules (Monters) but I don't supply it in this system because I'm not sure Gabor would appreciate it. I may reach out and see what he thinks.

**Fighters:**

- `Removing specialisms also removes the fighter tab. (if you drag a specialism back onto the sheet, the tab is visible again)`
Yes that was purposeful, as a Fighter MUST have a specialism. You can drag another specialism on to replace if you want.

**Students:**

- `a button to randomise Sciences would be great (like "Roll for Random Craft" for Germans)`
Yes, I did think about that but never did it....I'll see about adding that.

**Main-gauche:**
- `an entry under armour like the Parrying Dagger would also be great (I know it's easy to create yourself, but I was a bit stumped at first when I tried to add the AC bonus for the weapon until I realised that I just had to create it as an armour item)`
Since "main-gauche" is just the french name for "parrying dagger" I thought it wasn't worth adding the same thing twice. You can duplicate an entry and rename it, btw.

**Swedes:**

- [x] `no description` 
I don't know how I missed that! Thanks.
- [ ] `also, sometimes the font changes at the end of the description (e.g. jewish, hungarian, czech, cossacks)`
Argh...I see what you mean - *just*! The fonts appear so similar on my screen it's not noticeable. Fixing that will be a real pain, so I'll do that one day, but thanks for pointing it out!

I'll be dropping a new release soon to address all the ticked items.

Thank you for using the system - I hope you're enjoying it? Our campaign is great fun.

**Comment by chrisesharp** [comment]
> Regarding Fighter specialism: Another suggestion would be that if you remove the specialism, the button you used to select it with becomes visible again.

Ah, I see there was a bug now, as I had originally intended that to be the behaviour. Will be fixed in 3.0.9.

> Rolling for HP: On the sheet next to the HP is the dice symbol to roll for HP. When I use this, the level bonus is not taken into account. A Devil, Mephisto is level 6+2, so it has 6d8+2x6 HP. Using the sheet, however, only 5d8+8 are rolled, so the 2x6 HP due to the level bonus of +2 (or 2x5 because of the full HP for level 1) are missing.

Yep, I understand - fixed, in 3.0.8.

Re: Saves - ah, I understand you now! I hadn't realized some monsters used different preferences to Fighter, as the rules state that monsters use that! However, I have now fixed it so that if you use the Import function and specify saves, it uses those as-is rather than calculating them. It's a quick fix to make it work as it should have already, but something requiring more complex UI changes I will have to think carefully about to avoid it being too complicated. This will be fixed in 3.0.9.

Thank you so much for the extensive bug hunting!

**Comment by IYOV-git** [comment]
Great, thank you! And I'm happy to help.

**Comment by chrisesharp** [comment]
OK I'm going to close this issue as fixed in the latest release, but I will raise a separate issue about how I might deal with Save preference in a future enhancement.
