### ISSUE TITLE
Some Skill issues

### ISSUE THREAD

**Issue by IYOV-git** [chrisesharp/foundryvtt-helveczia#17]
Vagabonds
The Legends, Sneak attack and Traveller's luck specialisations take away skill slots.

![vag_skills](https://github.com/chrisesharp/foundryvtt-helveczia/assets/78300308/184cf8c8-36a6-4225-8f61-be6520ca3ec6)

Doctorate Clerics & Students
With a doctorate, both classes either get 6 points that they can spend in existing sciences or a new science skill that they can learn.

As far as I can tell, for students it is not possible to add another science skill at level 6. Clerics, on the other hand, get 6 extra skill slots when they reach level 6. Furthermore, a czech cleric/student gets an additional skill slot at level 4 and, in the case of czech clerics, in addition to the 6 slots at level 6.

I would implement the doctorate as a separate specialisation at level 6 (or 4 for czechs), where you can choose whether you want the points or another science skill.

**Comment by chrisesharp** [comment]
Ah yes, you are right.  The way I deal with the specialisms taking slots is to add a bonus number to the slots accordingly, but I am not calculating that correctly for Vagabonds or Students. I agree, the Doctorate would be better done as a Student specialism that requires one to be level 6.

**Comment by chrisesharp** [comment]
OK, I think all of these problems are now fixed in 3.1.0.

I couldn't really implement a choice of 6 skill points vs 1 new skill, as there is no way for me to really police it. So, I have added a new skill slot when you get the doctorate, and it will have to be up to the player to be honest whether they add skill bonuses to their skills or add a new skill but not both!

Please check out the new release and raise any new issues against that if you find any problems.

**Comment by chrisesharp** [comment]
FYI - the final version with al the ammendments is now 3.1.4
